# Generated by Django 5.1.5 on 2025-02-02 21:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='La URL única de la página.', unique=True, verbose_name='URL')),
                ('ultima_consulta', models.DateTimeField(blank=True, help_text='Fecha de la última consulta realizada a la página.', null=True, verbose_name='Última Consulta')),
                ('codigo_estado', models.IntegerField(blank=True, help_text='Código HTTP devuelto en la última consulta.', null=True, verbose_name='Código de Estado')),
                ('es_huerfana', models.BooleanField(default=False, help_text='Indica si la página es huérfana (sin enlaces entrantes).', verbose_name='¿Es Huérfana?')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la página está activa y debe mostrarse en la interfaz.', verbose_name='¿Está activa?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha en la que se creó el registro de la página.', verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['-ultima_consulta'],
                'indexes': [models.Index(fields=['url'], name='monitoring__url_ba39c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_destino', models.ForeignKey(help_text='La página a la que apunta el enlace.', on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_entrantes', to='monitoring_app.pagina', verbose_name='Página de Destino')),
                ('pagina_origen', models.ForeignKey(help_text='La página desde la que se origina el enlace.', on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_salientes', to='monitoring_app.pagina', verbose_name='Página de Origen')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'indexes': [models.Index(fields=['pagina_origen', 'pagina_destino'], name='monitoring__pagina__a8fa72_idx')],
                'constraints': [models.UniqueConstraint(fields=('pagina_origen', 'pagina_destino'), name='unique_enlace')],
            },
        ),
    ]
