# Generated by Django 5.1.5 on 2025-02-12 01:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceRoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_enlace_roto', models.URLField(help_text='La URL del enlace roto encontrado en la página.', verbose_name='URL del Enlace Roto')),
                ('codigo_estado', models.IntegerField(help_text='Código HTTP devuelto por el enlace roto.', verbose_name='Código de Estado')),
                ('detectado_en', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha en la que se detectó el enlace roto.', verbose_name='Detectado en')),
                ('pagina', models.ForeignKey(help_text='La página que contiene el enlace roto.', on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_rotos', to='monitoring_app.pagina', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Enlace Roto',
                'verbose_name_plural': 'Enlaces Rotos',
                'ordering': ['-detectado_en'],
                'indexes': [models.Index(fields=['pagina', 'url_enlace_roto'], name='monitoring__pagina__3c1c12_idx')],
            },
        ),
    ]
